### ISSUE TITLE
Plasma 6 support

### ISSUE THREAD

**Issue by leopoldsedev** [JonMagon/plasma-screendimmer#3]
Unfortunately it seems that Plasma 6 breaks all existing applets, including this one. It would be awesome if you had the time to migrate this applet to Plasma 6.

I found this [documentation](https://develop.kde.org/docs/plasma/widget/porting_kf6/).

**Comment by err0r2k** [comment]
A migration to Plasma 6 would be great! This is the best brightness tool.

**Comment by JonMagon** [comment]
I'll try to make some time this weekend.

**Comment by JonMagon** [comment]
Hi. Try adding a widget via the Add widgets menu, there is an option there to load from file: https://github.com/JonMagon/plasma-screendimmer/releases/download/1.0/plasma-screendimmer-1.0.plasmoid

**Comment by err0r2k** [comment]
> Hi. Try adding a widget via the Add widgets menu, there is an option there to load from file: https://github.com/JonMagon/plasma-screendimmer/releases/download/1.0/plasma-screendimmer-1.0.plasmoid

Works great! Thank you!
